GET https://localhost:44393/private/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyYTMwNzAwNC1iYzM0LTRkYTctODRhMi1hOTFmYTcwYTY2ZmIiLCJlbWFpbCI6Im1pY3JvQG1pY3JvLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvZXhwaXJhdGlvbiI6IjEwLzE5LzIwMjQgMjI6MjE6NTUiLCJuYmYiOjE3MjkzNzI5MTUsImV4cCI6MTcyOTM3NjUxNSwiaWF0IjoxNzI5MzcyOTE1LCJpc3MiOiJodHRwczovL2lkZW50aXR5Lm1pY3JvLmNvbSIsImF1ZCI6Imh0dHBzOi8vYXBwLm1pY3JvLmNvbSJ9.N28eZwokckxfmxnc8TCzmUrxlYsnDK5svdKjuNWBnKc

###