version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - docker-compose.env
    ports:
      - "5672:5672"
      - "15672:15672"
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - docker-compose.env
    volumes:
      - ./Resources/db-data:/var/lib/postgresql/data
      - ./Resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15433:80"
    env_file:
      - docker-compose.env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./Resources/pgadmin-data:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge